#include <stdio.h>

#define TAM 10
#define TAM_NAVIO 3
#define TAM_HAB 5

void inicializar_tabuleiro(int tabuleiro[TAM][TAM]) {
    for (int i = 0; i < TAM; i++)
            for (int j = 0; j < TAM; j++)
                        tabuleiro[i][j] = 0;
                        }

                        int dentro_limites(int x, int y) {
                            return x >= 0 && x < TAM && y >= 0 && y < TAM;
                            }

                            void posicionar_navio(int tabuleiro[TAM][TAM], int coords[TAM_NAVIO][2]) {
                                for (int i = 0; i < TAM_NAVIO; i++) {
                                        int l = coords[i][0];
                                                int c = coords[i][1];
                                                        if (dentro_limites(l, c)) {
                                                                    tabuleiro[l][c] = 3;
                                                                            }
                                                                                }
                                                                                }

                                                                                void gerar_cone(int habilidade[TAM_HAB][TAM_HAB]) {
                                                                                    for (int i = 0; i < TAM_HAB; i++) {
                                                                                            for (int j = 0; j < TAM_HAB; j++) {
                                                                                                        int centro = TAM_HAB / 2;
                                                                                                                    habilidade[i][j] = (j >= centro - i && j <= centro + i) ? 1 : 0;
                                                                                                                            }
                                                                                                                                }
                                                                                                                                }

                                                                                                                                void gerar_cruz(int habilidade[TAM_HAB][TAM_HAB]) {
                                                                                                                                    int centro = TAM_HAB / 2;
                                                                                                                                        for (int i = 0; i < TAM_HAB; i++) {
                                                                                                                                                for (int j = 0; j < TAM_HAB; j++) {
                                                                                                                                                            habilidade[i][j] = (i == centro || j == centro) ? 1 : 0;
                                                                                                                                                                    }
                                                                                                                                                                        }
                                                                                                                                                                        }

                                                                                                                                                                        void gerar_octaedro(int habilidade[TAM_HAB][TAM_HAB]) {
                                                                                                                                                                            int centro = TAM_HAB / 2;
                                                                                                                                                                                for (int i = 0; i < TAM_HAB; i++) {
                                                                                                                                                                                        for (int j = 0; j < TAM_HAB; j++) {
                                                                                                                                                                                                    habilidade[i][j] = (abs(i - centro) + abs(j - centro) <= centro) ? 1 : 0;
                                                                                                                                                                                                            }
                                                                                                                                                                                                                }
                                                                                                                                                                                                                }

                                                                                                                                                                                                                void aplicar_habilidade(int tabuleiro[TAM][TAM], int habilidade[TAM_HAB][TAM_HAB], int origem_l, int origem_c) {
                                                                                                                                                                                                                    int centro = TAM_HAB / 2;
                                                                                                                                                                                                                        for (int i = 0; i < TAM_HAB; i++) {
                                                                                                                                                                                                                                for (int j = 0; j < TAM_HAB; j++) {
                                                                                                                                                                                                                                            if (habilidade[i][j] == 1) {
                                                                                                                                                                                                                                                            int l = origem_l + (i - centro);
                                                                                                                                                                                                                                                                            int c = origem_c + (j - centro);
                                                                                                                                                                                                                                                                                            if (dentro_limites(l, c) && tabuleiro[l][c] != 3) {
                                                                                                                                                                                                                                                                                                                tabuleiro[l][c] = 5;
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                        void exibir_tabuleiro(int tabuleiro[TAM][TAM]) {
                                                                                                                                                                                                                                                                                                                                                            printf("\nTabuleiro:\n\n");
                                                                                                                                                                                                                                                                                                                                                                for (int i = 0; i < TAM; i++) {
                                                                                                                                                                                                                                                                                                                                                                        for (int j = 0; j < TAM; j++) {
                                                                                                                                                                                                                                                                                                                                                                                    printf("%d ", tabuleiro[i][j]);
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                    printf("\n");
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                        int main() {
                                                                                                                                                                                                                                                                                                                                                                                                            int tabuleiro[TAM][TAM];
                                                                                                                                                                                                                                                                                                                                                                                                                inicializar_tabuleiro(tabuleiro);

                                                                                                                                                                                                                                                                                                                                                                                                                    // Posiciona navios
                                                                                                                                                                                                                                                                                                                                                                                                                        int navio_horizontal[3][2] = {{1, 2}, {1, 3}, {1, 4}};
                                                                                                                                                                                                                                                                                                                                                                                                                            int navio_vertical[3][2] = {{5, 6}, {6, 6}, {7, 6}};
                                                                                                                                                                                                                                                                                                                                                                                                                                int navio_diag_principal[3][2] = {{2, 2}, {3, 3}, {4, 4}};
                                                                                                                                                                                                                                                                                                                                                                                                                                    int navio_diag_secundaria[3][2] = {{0, 9}, {1, 8}, {2, 7}};

                                                                                                                                                                                                                                                                                                                                                                                                                                        posicionar_navio(tabuleiro, navio_horizontal);
                                                                                                                                                                                                                                                                                                                                                                                                                                            posicionar_navio(tabuleiro, navio_vertical);
                                                                                                                                                                                                                                                                                                                                                                                                                                                posicionar_navio(tabuleiro, navio_diag_principal);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    posicionar_navio(tabuleiro, navio_diag_secundaria);

                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Matrizes de habilidades
                                                                                                                                                                                                                                                                                                                                                                                                                                                            int cone[TAM_HAB][TAM_HAB], cruz[TAM_HAB][TAM_HAB], octaedro[TAM_HAB][TAM_HAB];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                gerar_cone(cone);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gerar_cruz(cruz);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        gerar_octaedro(octaedro);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Aplicar habilidades no tabuleiro
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                aplicar_habilidade(tabuleiro, cone, 2, 2);       // Cone centrado em (2,2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    aplicar_habilidade(tabuleiro, cruz, 5, 5);       // Cruz centrada em (5,5)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        aplicar_habilidade(tabuleiro, octaedro, 7, 2);   // Octaedro centrado em (7,2)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Mostrar resultado final
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                exibir_tabuleiro(tabuleiro);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }